'use strict';

const BATTLE_EVENT_DEFINITIONS=Object.freeze([
 {id:'supply_tide',name:'补给潮汐',category:'reward',label:'奖励事件',duration:20,desc:'敌军攻势暂缓，战场析出经验与修复补给。'},
 {id:'core_meteor',name:'源核陨星',category:'reward',label:'奖励事件',duration:35,desc:'击破高能源核陨星，获得一次直升Ⅲ级或觉醒机会。'},
 {id:'mirror_invasion',name:'镜像入侵',category:'danger',label:'危险事件',duration:26,desc:'敌军镜像同步进入战场，本体被击毁后镜像崩解。'},
 {id:'hunt_reversal',name:'猎杀反转',category:'danger',label:'危险事件',duration:30,desc:'限时击毁悬赏精英；失败后目标将进入暴走状态。'},
 {id:'memory_echo',name:'记忆回声',category:'rare',label:'稀有事件',duration:15,desc:'上一轮作战残影跨越时序，短暂协助当前驾驶员。'},
 {id:'emp_storm',name:'电磁风暴',category:'environment',label:'环境异常',duration:25,desc:'随机雷击同时威胁敌我，制导系统出现短暂扰动。'},
 {id:'gravity_anomaly',name:'引力异常',category:'environment',label:'环境异常',duration:25,desc:'引力核心牵引敌弹、掉落物与小型敌军。'},
 {id:'meteor_rain',name:'陨石雨',category:'environment',label:'环境异常',duration:30,desc:'高速陨石穿越战区，可同时伤害玩家与敌军。'}
]);
const BATTLE_EVENT_BY_ID=Object.freeze(Object.fromEntries(BATTLE_EVENT_DEFINITIONS.map(e=>[e.id,e])));

class BattleEventSystem{
 constructor(){this.reset()}
 reset(){this.deck=[];this.active=null;this.nextAt=135+Math.random()*35;this.warning=null;this.enabled=true;this.spawnCd=0;this.fx=[];this.gravity=null;this.huntTarget=null;this.echoCd=0;this.lastEventAt=-999;this.buildDeck();this.hideHud()}
 buildDeck(){const rewards=this.pick(BATTLE_EVENT_DEFINITIONS.filter(e=>e.category==='reward'),1);const dangers=this.pick(BATTLE_EVENT_DEFINITIONS.filter(e=>e.category==='danger'),1);const env=this.pick(BATTLE_EVENT_DEFINITIONS.filter(e=>e.category==='environment'),1);const used=new Set([...rewards,...dangers,...env].map(e=>e.id));let rest=BATTLE_EVENT_DEFINITIONS.filter(e=>!used.has(e.id));if(Math.random()>.35)rest=rest.filter(e=>e.category!=='rare').concat(rest.filter(e=>e.category==='rare'));const fourth=this.pick(rest,1);this.deck=this.shuffle([...rewards,...dangers,...env,...fourth]).map(e=>e.id)}
 pick(arr,n){return this.shuffle([...arr]).slice(0,n)}
 shuffle(arr){for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
 getHud(){let root=document.getElementById('battleEventHud');if(!root){root=document.createElement('div');root.id='battleEventHud';root.className='battle-event-hud hidden';document.getElementById('app')?.appendChild(root)}return root}
 hideHud(){document.getElementById('battleEventHud')?.classList.add('hidden')}
 showHud(def,time,warning=false){const root=this.getHud();root.className=`battle-event-hud ${def.category} ${warning?'warning':''}`;root.innerHTML=`<small>${warning?'异常预警':def.label}</small><b>${def.name}</b><span>${warning?'即将进入战区':Math.max(0,Math.ceil(time))+'s'}</span>`}
 canStart(){return running&&!paused&&!dying&&state==='game'&&!enemies.some(e=>e.boss)&&!awakeningSystem.pending}
 update(dt){if(!this.enabled||!running||dying)return;this.updateFx(dt);if(this.warning){this.warning.time-=dt;this.showHud(this.warning.def,this.warning.time,true);if(this.warning.time<=0){const id=this.warning.def.id;this.warning=null;this.start(id)}return}if(!this.active){if(this.deck.length&&elapsed>=this.nextAt&&this.canStart()){this.warning={def:BATTLE_EVENT_BY_ID[this.deck.shift()],time:5};this.showHud(this.warning.def,5,true)}return}this.active.time-=dt;this.showHud(this.active.def,this.active.time,false);this.updateActive(dt);if(this.active&&this.active.time<=0)this.end(false)}
 start(id,forced=false){const def=BATTLE_EVENT_BY_ID[id];if(!def)return false;if(this.active)this.end(true);this.active={def,time:def.duration,forced,success:false};this.spawnCd=0;this.lastEventAt=elapsed;toast(`${def.label} · ${def.name}`);if(id==='core_meteor')this.spawnCoreMeteor();if(id==='hunt_reversal')this.spawnHuntTarget();if(id==='gravity_anomaly')this.gravity={x:W*(.28+Math.random()*.44),y:H*(.25+Math.random()*.3),life:def.duration};if(id==='memory_echo')this.echoCd=0;return true}
 end(cancelled=false){if(!this.active)return;const id=this.active.def.id;if(id==='hunt_reversal'&&this.huntTarget&&this.huntTarget.hp>0&&!cancelled){this.huntTarget.enraged=true;this.huntTarget.v*=1.55;this.huntTarget.shoot=Math.max(320,this.huntTarget.shoot*.48);this.huntTarget.hp=Math.min(this.huntTarget.max,this.huntTarget.hp+this.huntTarget.max*.45);toast('猎杀失败 · 悬赏目标进入暴走')}if(id==='gravity_anomaly')this.gravity=null;if(id==='meteor_rain')this.fx=this.fx.filter(f=>f.type!=='meteor');this.active=null;this.huntTarget=null;this.hideHud();this.nextAt=elapsed+95+Math.random()*45}
 triggerRandom(){const pool=BATTLE_EVENT_DEFINITIONS.filter(e=>!this.active||e.id!==this.active.def.id);return this.start(pool[Math.floor(Math.random()*pool.length)].id,true)}
 spawnCoreMeteor(){enemies.push({type:'eventMeteor',eventMeteor:true,x:W/2,y:115,r:40,hp:720,max:720,v:12,shoot:999999,age:0,dir:1})}
 spawnHuntTarget(){const candidates=['heavy','barrage','carrier','jammer','sniper'];const e=makeEnemy(candidates[Math.floor(Math.random()*candidates.length)]);e.x=W/2;e.y=100;e.huntTarget=true;e.hp=Math.round(e.hp*2.4);e.max=e.hp;e.v*=1.12;this.huntTarget=e;enemies.push(e)}
 updateActive(dt){const id=this.active.def.id;this.spawnCd-=dt;if(id==='supply_tide'&&this.spawnCd<=0){this.spawnCd=.72;const salvage=awakeningSystem.get('repair')?.id==='repair_salvage';const type=salvage||Math.random()<.78?'eventXp':'repair';pickups.push({type,x:35+Math.random()*(W-70),y:-15,vx:(Math.random()-.5)*22,vy:58,life:9,r:type==='eventXp'?6:8,heal:14,xp:18})}
 if(id==='mirror_invasion'&&this.spawnCd<=0){this.spawnCd=2.8;const originals=enemies.filter(e=>!e.boss&&!e.eventMirror&&!e.eventMeteor).slice(-2);for(const host of originals){const m=makeEnemy(host.type);m.x=Math.max(25,Math.min(W-25,W-host.x));m.y=host.y+18;m.hp=Math.max(12,Math.round(host.max*.34));m.max=m.hp;m.eventMirror=true;m.mirrorHost=host;m.rewardless=true;enemies.push(m)}}
 if(id==='emp_storm'&&this.spawnCd<=0){this.spawnCd=1.1+Math.random()*1.4;const x=35+Math.random()*(W-70);this.fx.push({type:'lightningWarning',x,life:.7,max:.7});setTimeout(()=>{if(!this.active||this.active.def.id!=='emp_storm')return;this.fx.push({type:'lightningStrike',x,life:.32,max:.32});for(const e of [...enemies])if(Math.abs(e.x-x)<34&&damageEnemy(e,70)){const idx=enemies.indexOf(e);if(idx>=0)enemies.splice(idx,1)}if(Math.abs(player.x-x)<30)damagePlayer(13)},700)}
 if(id==='meteor_rain'&&this.spawnCd<=0){this.spawnCd=.65+Math.random()*.65;this.fx.push({type:'meteor',x:Math.random()*(W+160)-80,y:-60,vx:-70+Math.random()*140,vy:300+Math.random()*120,r:10+Math.random()*10,life:5,spin:Math.random()*Math.PI*2,spinSpeed:(Math.random()>.5?1:-1)*(1.2+Math.random()*1.8),seed:Math.random()*999})}
 if(id==='gravity_anomaly'&&this.gravity){const g=this.gravity;for(const b of enemyBullets){const dx=g.x-b.x,dy=g.y-b.y,d=Math.hypot(dx,dy)||1;b.vx+=dx/d*105*dt;b.vy+=dy/d*105*dt}for(const p of pickups){const dx=g.x-p.x,dy=g.y-p.y,d=Math.hypot(dx,dy)||1;p.vx=(p.vx||0)+dx/d*75*dt;p.vy=(p.vy||0)+dy/d*75*dt}for(const e of enemies)if(!e.boss&&!e.eventMeteor){const dx=g.x-e.x,dy=g.y-e.y,d=Math.hypot(dx,dy)||1;e.x+=dx/d*18*dt;e.y+=dy/d*18*dt}}
 if(id==='memory_echo'){this.echoCd-=dt;if(this.echoCd<=0){this.echoCd=.16;for(const o of [-34,34])bullets.push({x:player.x+o,y:player.y+8,vx:0,vy:-610,r:3,d:player.damage*.42,life:2.2,source:'memoryEcho'})}}
 }
 updateFx(dt){for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.life-=dt;if(f.type==='meteor'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.spin=(f.spin||0)+(f.spinSpeed||1.5)*dt;for(const e of [...enemies])if(Math.hypot(e.x-f.x,e.y-f.y)<e.r+f.r){if(damageEnemy(e,82)){const idx=enemies.indexOf(e);if(idx>=0)enemies.splice(idx,1)}f.life=0;break}if(Math.hypot(player.x-f.x,player.y-f.y)<player.r+f.r){damagePlayer(16);f.life=0}if(f.y>H+120||f.x<-180||f.x>W+180)f.life=0}if(f.life<=0)this.fx.splice(i,1)}}
 onEnemyKilled(e){if(e.eventMeteor){this.active&&(this.active.success=true);this.end(true);setTimeout(()=>awakeningSystem.openMeteorReward(),320);return}if(e.huntTarget){this.active&&(this.active.success=true);xp+=Math.round(nextXp*.7);addBarrierCharge(32);toast('猎杀完成 · 获得高额同步能量');this.end(true)}if(e.mirrorHost){e.mirrorHost=null}for(let i=enemies.length-1;i>=0;i--)if(enemies[i].eventMirror&&enemies[i].mirrorHost===e)enemies.splice(i,1)}
 draw(){ctx.save();ctx.globalCompositeOperation='lighter';if(this.gravity){const g=this.gravity,p=1+Math.sin(elapsed*4)*.08;ctx.strokeStyle='rgba(177,105,255,.75)';ctx.shadowBlur=28;ctx.shadowColor='#8c53ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(g.x,g.y,34*p,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='rgba(92,224,255,.48)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(g.x,g.y,57/p,elapsed,-elapsed+Math.PI*1.4);ctx.stroke()}for(const f of this.fx){if(f.type==='lightningWarning'){ctx.globalAlpha=f.life/f.max;ctx.strokeStyle='#ff6b67';ctx.lineWidth=2;ctx.beginPath();ctx.arc(f.x,player.y,26+(1-f.life/f.max)*14,0,Math.PI*2);ctx.stroke()}if(f.type==='lightningStrike'){ctx.globalAlpha=f.life/f.max;ctx.strokeStyle='#e9ffff';ctx.shadowBlur=24;ctx.shadowColor='#61dcff';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(f.x,0);ctx.lineTo(f.x+Math.sin(elapsed*60)*8,H);ctx.stroke()}if(f.type==='meteor'){ctx.globalAlpha=Math.min(1,f.life);ctx.save();ctx.translate(f.x,f.y);const flight=Math.atan2(f.vy,f.vx)+Math.PI/2;ctx.rotate(flight);ctx.shadowBlur=24;ctx.shadowColor='#ff2838';const tailLength=f.r*(4.4+Math.sin(elapsed*10+f.seed)*.35);const tail=ctx.createLinearGradient(0,-f.r*.1,0,-tailLength);tail.addColorStop(0,'rgba(255,245,205,.92)');tail.addColorStop(.16,'rgba(255,74,46,.9)');tail.addColorStop(.52,'rgba(218,14,35,.58)');tail.addColorStop(1,'rgba(90,0,18,0)');ctx.fillStyle=tail;ctx.beginPath();ctx.moveTo(-f.r*.42,-f.r*.25);ctx.quadraticCurveTo(-f.r*.78,-tailLength*.45,0,-tailLength);ctx.quadraticCurveTo(f.r*.78,-tailLength*.45,f.r*.42,-f.r*.25);ctx.closePath();ctx.fill();ctx.rotate((f.spin||0)-flight);const rock=ctx.createRadialGradient(-f.r*.28,-f.r*.35,1,0,0,f.r);rock.addColorStop(0,'#fff0b8');rock.addColorStop(.17,'#ff704d');rock.addColorStop(.52,'#d7192e');rock.addColorStop(1,'#39050d');ctx.fillStyle=rock;ctx.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI*2/10;const wobble=.72+(((i*43+Math.floor(f.seed))%13)/38);const rr=f.r*wobble;i?ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr):ctx.moveTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,122,88,.88)';ctx.lineWidth=1.6;ctx.stroke();ctx.fillStyle='rgba(72,0,10,.5)';for(let i=0;i<3;i++){const a=f.seed+i*2.1;ctx.beginPath();ctx.arc(Math.cos(a)*f.r*.36,Math.sin(a)*f.r*.32,f.r*(.09+i*.018),0,Math.PI*2);ctx.fill()}ctx.restore()}}ctx.restore()}
}
const battleEventSystem=new BattleEventSystem();window.IWBattleEventSystem=battleEventSystem;
