'use strict';
const IW_SAVE_KEY='infinityWingsSaveV1';
const IW_SAVE_SLOT_PREFIX='infinityWingsSaveSlotV1:';
const IW_ACTIVE_SLOT_KEY='infinityWingsActiveSaveSlotV1';
const IW_SAVE_VERSION=1;
const IW_LEGACY_KEYS=['iwArchiveCoreLevelsV2','iwArchiveCoresV1','iwArchiveEnemiesV1','iwArchiveEnemyDefeatedV1','iwRunRecordsV1','infinityWingsPilotIdV2'];
function iwDefaultSave(){return{version:IW_SAVE_VERSION,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),profile:{pilotId:1,totalRuns:0,selectedFighter:'infinity'},story:{currentChapter:1,chapterOneCompleted:false,chapterTwoUnlocked:false,riftUnlocked:false,wrecksFound:0,wrecks:[false,false,false,false],introSeen:false},progression:{highestThreat:0,cores:{},enemies:[],defeated:[],fighters:['infinity']},runCheckpoint:null,records:[]}}
function iwNormalizeSave(raw){const base=iwDefaultSave(),save=raw&&typeof raw==='object'?raw:{},fighters=Array.isArray(save.progression?.fighters)?save.progression.fighters.filter(id=>typeof id==='string'):base.progression.fighters;return{...base,...save,version:IW_SAVE_VERSION,profile:{...base.profile,...save.profile},story:{...base.story,...save.story,wrecks:Array.isArray(save.story?.wrecks)?save.story.wrecks.slice(0,4).map(Boolean):base.story.wrecks},progression:{...base.progression,...save.progression,cores:save.progression?.cores&&typeof save.progression.cores==='object'?save.progression.cores:{},enemies:Array.isArray(save.progression?.enemies)?save.progression.enemies:[],defeated:Array.isArray(save.progression?.defeated)?save.progression.defeated:[],fighters:[...new Set(['infinity',...fighters])]},runCheckpoint:null,records:Array.isArray(save.records)?save.records.slice(0,20):[]}}
function iwSaveHasProgress(save){return Boolean(save&&(save.story?.introSeen||save.story?.chapterOneCompleted||save.story?.wrecksFound>0||save.profile?.totalRuns>0||save.progression?.highestThreat>0||(save.progression?.fighters?.length||0)>1||Object.keys(save.progression?.cores||{}).length))}
function iwSlotKey(slot){return IW_SAVE_SLOT_PREFIX+Math.max(1,Math.min(3,Number(slot)||1))}
const saveSystem={
 data:null,migrationPending:false,activeSlot:0,
 load(){try{const legacyRaw=localStorage.getItem(IW_SAVE_KEY),hasSlots=[1,2,3].some(slot=>localStorage.getItem(iwSlotKey(slot)));if(!hasSlots&&legacyRaw){const legacy=iwNormalizeSave(JSON.parse(legacyRaw));if(iwSaveHasProgress(legacy)){localStorage.setItem(iwSlotKey(1),JSON.stringify(legacy));localStorage.setItem(IW_ACTIVE_SLOT_KEY,'1')}}this.activeSlot=Math.max(0,Math.min(3,Number(localStorage.getItem(IW_ACTIVE_SLOT_KEY))||0));const slotRaw=this.activeSlot?localStorage.getItem(iwSlotKey(this.activeSlot)):null;if(slotRaw)this.data=iwNormalizeSave(JSON.parse(slotRaw))}catch(error){console.warn('永久存档损坏，已创建安全的新存档',error)}if(!this.data){this.data=iwDefaultSave();this.migrationPending=IW_LEGACY_KEYS.some(key=>localStorage.getItem(key)!==null)}return this.data},
 commit(){this.data=iwNormalizeSave(this.data);this.data.updatedAt=new Date().toISOString();if(this.activeSlot){localStorage.setItem(iwSlotKey(this.activeSlot),JSON.stringify(this.data));localStorage.setItem(IW_ACTIVE_SLOT_KEY,String(this.activeSlot))}localStorage.setItem(IW_SAVE_KEY,JSON.stringify(this.data));return this.data},
 listSlots(){return [1,2,3].map(slot=>{try{const raw=localStorage.getItem(iwSlotKey(slot));return raw?iwNormalizeSave(JSON.parse(raw)):null}catch{return null}})},
 hasAnySlot(){return this.listSlots().some(Boolean)},
 activateSlot(slot){const raw=localStorage.getItem(iwSlotKey(slot));if(!raw)return false;this.activeSlot=Math.max(1,Math.min(3,Number(slot)||1));this.data=iwNormalizeSave(JSON.parse(raw));localStorage.setItem(IW_ACTIVE_SLOT_KEY,String(this.activeSlot));localStorage.setItem(IW_SAVE_KEY,JSON.stringify(this.data));return this.data},
 createSlot(slot){this.activeSlot=Math.max(1,Math.min(3,Number(slot)||1));this.data=iwDefaultSave();localStorage.setItem(IW_ACTIVE_SLOT_KEY,String(this.activeSlot));return this.commit()},
 deleteSlot(slot){const target=Math.max(1,Math.min(3,Number(slot)||1));localStorage.removeItem(iwSlotKey(target));if(this.activeSlot===target){this.activeSlot=0;this.data=iwDefaultSave();localStorage.removeItem(IW_ACTIVE_SLOT_KEY)}return true},
 migrate(){const data=this.data||this.load();if(!this.activeSlot){const emptyIndex=this.listSlots().findIndex(save=>!save);this.activeSlot=emptyIndex>=0?emptyIndex+1:1}const parse=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};const cores=parse('iwArchiveCoreLevelsV2',{});const legacyCores=parse('iwArchiveCoresV1',[]);for(const id of legacyCores)cores[id]=Math.max(1,Number(cores[id])||0);data.progression.cores=cores;data.progression.enemies=parse('iwArchiveEnemiesV1',[]);data.progression.defeated=parse('iwArchiveEnemyDefeatedV1',[]);data.records=parse('iwRunRecordsV1',[]).slice(0,20);data.profile.pilotId=Math.max(1,Number(localStorage.getItem('infinityWingsPilotIdV2'))||1);data.profile.totalRuns=Math.max(data.profile.totalRuns,data.records.length);this.migrationPending=false;return this.commit()},
 markIntroSeen(){this.data.story.introSeen=true;this.commit()},
 recordRun(record){this.data.profile.totalRuns++;this.data.progression.highestThreat=Math.max(this.data.progression.highestThreat,record.threatIndex||0);this.data.records=[record,...this.data.records].slice(0,20);this.commit()},
 saveCheckpoint(){this.data.runCheckpoint=null;return this.commit()},
 clearCheckpoint(){this.data.runCheckpoint=null;this.commit()},
 selectFighter(id){const fighters=this.data.progression.fighters||['infinity'];this.data.profile.selectedFighter=fighters.includes(id)?id:'infinity';this.commit();return this.data.profile.selectedFighter},
 unlockFighter(id){const allowed=['infinity','laser','drone','missile','thunder'];if(!allowed.includes(id))return false;const fighters=this.data.progression.fighters;if(fighters.includes(id))return false;fighters.push(id);this.commit();return true},
 unlockAllFighters(){this.data.progression.fighters=['infinity','laser','drone','missile','thunder'];return this.commit()},
 completeChapterOne(){if(this.data.story.chapterOneCompleted)return false;Object.assign(this.data.story,{chapterOneCompleted:true,chapterTwoUnlocked:true,currentChapter:2,wrecksFound:4,wrecks:[true,true,true,true]});this.data.progression.fighters=['infinity','laser','drone','missile','thunder'];this.commit();return true},
 export(){this.commit();return JSON.stringify(this.data,null,2)},
 import(text){const parsed=JSON.parse(text);if(!parsed||typeof parsed!=='object'||!parsed.story)throw new Error('无效的无限之翼存档');if(!this.activeSlot){const empty=this.listSlots().findIndex(save=>!save);if(empty<0)throw new Error('三个存档槽位已满，请先删除一个存档');this.activeSlot=empty+1}this.data=iwNormalizeSave(parsed);return this.commit()},
 clear(){if(this.activeSlot)localStorage.removeItem(iwSlotKey(this.activeSlot));localStorage.removeItem(IW_SAVE_KEY);localStorage.removeItem(IW_ACTIVE_SLOT_KEY);this.activeSlot=0;this.data=iwDefaultSave();this.migrationPending=false;return this.data}
};
saveSystem.load();window.IWSave=saveSystem;
